### PR TITLE
My application page implementation

### PR DESCRIPTION
**Pull request by alishba-a8**
Implemented my application.
For now, I have made a popup for the action step. 
The Date of Application still needs to be implemented after the PDF upload PR is finished

image

image

### CODE REVIEW

**Review by al-yanna — APPROVED** [review]

**Review by nikkikapadia — COMMENTED** [review]
The company name isn't showing up in the company column, i think you might need to change `item.company` to `item.companyName`. I'm going on the fly so maybe fact check me on that :) 
image

**Comment by alishba-a8** [comment]
Heyyyy. So I am pulling the Company's Information from the posting table and there is no field for the company's name, only the logo field. The Application table doesn't have that field either. 

Should I add the Name field to the posting table?

**Comment by alishba-a8** [comment]
Never mind, ignore the comment. I found where the company name is stored. I'll add it in.

**Comment by alishba-a8** [comment]
Added the company name.

image

**Review by nikkikapadia — APPROVED** [review]
lgtm

**Review by al-yanna — APPROVED** [review]

**Pull request merged**
